/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef LABWC_CORNER_H
#define LABWC_CORNER_H

enum lab_corner {
	LAB_CORNER_UNKNOWN = 0,
	LAB_CORNER_TOP_LEFT = 1 << 0,
	LAB_CORNER_TOP_RIGHT = 1 << 1,
	LAB_CORNER_BOTTOM_LEFT = 1 << 2,
	LAB_CORNER_BOTTOM_RIGHT = 1 << 3,
	LAB_CORNER_ALL = (LAB_CORNER_TOP_LEFT | LAB_CORNER_TOP_RIGHT
		| LAB_CORNER_BOTTOM_LEFT | LAB_CORNER_BOTTOM_RIGHT),
};

#endif /* LABWC_CORNER_H */
