#!/bin/bash

options="\
	--enable=all \
	--suppress=missingInclude \
	--suppress=unusedFunction \
	--suppress=unmatchedSuppression \
"

for f in  $(find src/ -name "*.c"); do
	cppcheck ${options} "${f}"
done

